### ISSUE TITLE
What custom mods?

### ISSUE THREAD

**Issue by deepseek** [spiyer99/detectron2#1]
@spiyer99 
What changes did you make to detectron2 and why

**Comment by spiyer99** [comment]
@deepseek Added RandomContrast, RandomBrightness, RandomSaturation, RandomLighting to TransformsGens in detection_utils.py.

We wanted to add more ways to augment the data to increase the accuracy of our model.

**Comment by deepseek** [comment]
Have you tested the detection improvement?
training/testing with detectron2 vs training with your detectron2 augmentations?
