### ISSUE TITLE
integrate Centermask2

### ISSUE THREAD

**Issue by deepseek** [spiyer99/detectron2#2]
@spiyer99 integrate [Centermask2](https://github.com/youngwanLEE/centermask2) to this repo

**Comment by spiyer99** [comment]
Thanks @deepseek will do this

**Comment by deepseek** [comment]
sadly, after testing Centermask, the results were really bad:
https://github.com/davamix/cats-localization/issues/6

sorry, but it's better that you don't integrate it, Centermask seems not to be practical.
sorry
